name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore dependencies
        run: dotnet restore src/Dobrasync.CLI/Dobrasync.CLI.sln

      - name: Build the project
        run: dotnet build src/Dobrasync.CLI/Dobrasync.CLI.sln --configuration Release

      - name: Publish the app
        run: dotnet publish src/Dobrasync.CLI/Dobrasync.CLI.sln --configuration Release --output ./publish

      - name: Create release artifact (ZIP)
        run: |
          mkdir -p ./artifacts
          zip -r ./artifacts/bin.zip ./publish/*

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/bin.zip"
          tag: "${{ github.event.inputs.version }}"
